version: '2.21'
networks:
  app-network:
    driver: bridge
services:
  mysqldb:
    image: basswood/mysqldb
    container_name: mysqldb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - $PWD/data:/var/lib/mysql
    healthcheck:
      test: /opt/health-check.sh || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  webauthn:
    image: basswood/webauthn
    container_name: webauthn
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - BASSWOOD_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/webauthn_basswood
      - BASSWOOD_DATASOURCE_USER=basswood
      - BASSWOOD_SECURITY_KEYSTORE_KEYSTOREFILE=file:///opt/basswood/keystore/basswood-not-for-production-keystore.p12
      - BASSWOOD_SECURITY_KEYSTORE_KEYSTORECONFIGFILE=file:///opt/basswood/keystore/keystore-config.json
      - BASSWOOD_SECURITY_KEYSTORE_LOADJWKFILEONSTARTUP=true
      - BASSWOOD_SECURITY_JWT_FILTER_DISABLE=false
      - BASSWOOD_SECURITY_JWT_PRINTNEWTOKENONSTARTUP=false
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    volumes:
      - ./secrets:/opt/basswood/keystore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9080:9080"
      - "5005:5005"
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:9080/actuator/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  authenticator:
    image: basswood/authenticator
    container_name: authenticator
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5006,server=y,suspend=n"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9090:9090"
      - "5006:5006"
    networks:
      - app-network
    healthcheck:
      test: curl --fail http://localhost:9090/actuator/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  newman:
    image: postman/newman:alpine
    container_name: newman
    depends_on:
      mysqldb:
        condition: service_healthy
      webauthn:
        condition: service_healthy
      authenticator:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - $PWD/newman:/etc/newman
    command:
      run basswood-test.postman_collection.json
      -e basswood-webauthn-test.postman_environment.json
      -r json,cli
      --reporter-json-export=results/newman-results.json
